apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HamzaQazi10/infrastructure-staging.git
    targetRevision: HEAD
    path: Infrastructure/infrastructure
  destination: 
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
