#-----------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      labels:
        app: cart-app
    spec:
     # nodeSelector:
      #  kubernetes.io/hostname: cluster1-m03
      containers:
      - name: cart-app-container
        image: hamzaarshad10/cartservice:latest
        ports:
        - containerPort: 7070
        env:
          - name: REDIS_ADDR
            value: "redis-service:6379"
          - name: SERVICE_NAME
            value: cart
          #- name: REDIS_HOST
           # value: redis-service
          #- name: REDIS_PORT
           # value: "6379"  
          #- name: REDIS_PASSSWORD
           # value: "70701" 
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: staging
spec:
  selector:
    app: cart-app
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
  #type: NodePort 
