#-----------POD CREATED
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-app
  template:
    metadata:
      labels:
        app: product-catalog-app
    spec:
     # nodeSelector:
      #  kubernetes.io/hostname: cluster1-m03
      containers:
      - name: productapp-app-container
        image: hamzaarshad10/productcatalogservice:latest
        ports:
        - containerPort: 3550  
        env:  
          - name: PORT
            value: "3550"
          - name: SERVICE_NAME
            value: productcatalog
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalog
  namespace: staging
spec:
  selector:
    app: product-catalog-app
  ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550
  #type: NodePort 
